theme: jekyll-theme-minimal
lang: en-US
title: ZhiYuan Jia (Tainger)
description: Hi everyone, This is Tainger, nice to meet you! <br/><br/> TODO <br/><br/> TODO。
show_downloads: false
logo: images/avatar.jpg
